service: workouts

provider:
  name: aws
  runtime: dotnetcore1.0

package:
  artifact: bin/release/netcoreapp1.0/publish/deploy-package.zip

functions:
  getnextworkout:
    handler: CsharpHandlers::Workouts.Workouts::GetNextWorkout
    events:
      - http:
          path: workouts
          method: get
          cors: true
  saveexercise:
    handler: CsharpHandlers::Workouts.Workouts::SaveExercise
    events:
      - http:
          path: workouts
          method: post
          cors: true

